'use strict';
const profile=window.furnaceProfile;
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=name=>encodeURIComponent(name);
let state,mode='observation',view='schematic',toastTimer,sequenceTimer;
const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function addEvidence(source,component,observation,confidence='Direct technician report',extra={}){
 const item={id:`EV-${String(state.evidence.length+1).padStart(3,'0')}`,timestamp:now(),source,component,observation,confidence,provenance:'Technician report',...extra};state.evidence.push(item);return item;
}
function reset(){
 clearInterval(sequenceTimer);state={score:71,stage:5,selected:'sensor',sensorState:'SUSPECTED',step:null,inspection:null,correctiveActions:[],tests:[],validationResults:[],observations:[],evidence:[],paused:null,restored:false};
 addEvidence('Equipment documentation','Equipment identity',`Model ${profile.model}; parts configuration retrieved from supplied parts PDF.`,'Document-backed identity; physical label requires confirmation',{provenance:'Service documentation',link:profile.documentation});
 addEvidence('Parts documentation','Flame sensor','Key 19: R44745-001 SENSOR-FLAME; Part Number column 98M87. PDF page 3 (printed page 2).','Document-backed component reference',{provenance:'Service documentation',link:profile.documentation});
 addEvidence('Supplied reference screenshot','Flame sensor','A supplied screenshot shows the sensor near the burner compartment. This is reference material, not a current-condition assessment.','Reference image only',{provenance:'Service documentation',image:profile.photos.sensor});
 addEvidence('Demo complaint','Flame proving system','Furnace starts but shuts down shortly after ignition.','Seeded demonstration observation');
 state.observations.push(state.evidence.at(-1));mode='observation';view='schematic';render();renderInput();
}
function componentStatus(c){return c.id==='sensor'?state.sensorState:'UNKNOWN'}
function observed(c){if(c.id==='sensor')return state.restored?'Technician reports continued operation after inspection and retest. Flame signal remains unmeasured.':state.inspection?`Inspection recorded: ${state.inspection}. ${state.correctiveActions.length?'Cleaning action confirmed.':''}`:'Ignition followed by shutdown reported; sensor condition and flame signal unknown.';if(c.id==='burners')return state.restored?'Burner operation reportedly continues during observed retest.':'Ignition reported; sustained operation not established.';return 'No direct measurement or inspection result recorded.'}
function render(){
 $('#score').innerHTML=`${state.score}<span>%</span>`;$('#ring').style.background=`conic-gradient(var(--teal) ${state.score}%,#dce4de 0)`;
 $('#healthLabel').textContent=state.restored?'Normal operation reported':state.score===79?'Inspection findings recorded':'Operating fault reported';
 $('#sessionState').textContent=state.restored?'● POST-SERVICE OPERATION VERIFIED IN DEMO':state.paused?'● ADDITIONAL EVIDENCE REQUIRED':state.step!==null?'● GUIDED PROCEDURE IN PROGRESS':'● FAULT ISOLATION IN PROGRESS';$('#sessionState').style.color=state.restored?'var(--teal)':'var(--amber)';
 $('#evidenceCount').textContent=`${state.evidence.length} service log entries · call in progress`;
 $('#journey').innerHTML=profile.stages.map((s,i)=>`<div class="${i<state.stage?'done':i===state.stage?'current':''}"><i>${i<state.stage?'✓':String(i+1).padStart(2,'0')}</i>${s}</div>`).join('');
 renderDiagram();renderComponent();renderReasoning();renderSequence();
}
function renderDiagram(){
 $('#schematicBtn').classList.toggle('active',view==='schematic');$('#photoBtn').classList.toggle('active',view==='photo');
 if(view==='photo'){$('#diagramStage').innerHTML=`<img src="${asset(profile.photos.overview)}" alt="Supplied reference photograph of the open furnace"><span class="photo-caption">Supplied reference · equipment condition is not live</span>`;return}
 const shapes=profile.components.map(c=>{
 let detail='';
 if(c.id==='burners')detail=[0,1,2,3].map(i=>`<rect x="${c.x+16+i*52}" y="${c.y+14}" width="31" height="31" rx="5" fill="#becdc1"/><path d="M${c.x+31+i*52} ${c.y+17}v25" stroke="#f4faf6" stroke-width="3"/>`).join('');
 if(c.id==='inducer'||c.id==='blower')detail=`<circle cx="${c.x+c.w/2}" cy="${c.y+c.h/2-5}" r="${c.id==='blower'?35:32}" fill="none" stroke="#91a79a" stroke-width="3"/><circle cx="${c.x+c.w/2}" cy="${c.y+c.h/2-5}" r="10" fill="#a6b8aa"/>${[0,60,120,180,240,300].map(a=>`<path d="M${c.x+c.w/2+10} ${c.y+c.h/2-5}q24 -18 18 -26" transform="rotate(${a} ${c.x+c.w/2} ${c.y+c.h/2-5})" fill="none" stroke="#a6b8aa" stroke-width="5"/>`).join('')}`;
 if(c.id==='sensor'||c.id==='igniter')detail=`<path d="M${c.x+20} ${c.y+10}v30l8 -8" stroke="${c.id==='sensor'?'#ba822c':'#8f9e93'}" stroke-width="4" fill="none"/><rect x="${c.x+14}" y="${c.y+36}" width="13" height="10" fill="#b5c2b7"/>`;
 if(c.id==='control')detail=[0,1,2,3].map(i=>`<rect x="${c.x+12}" y="${c.y+12+i*14}" width="20" height="7" fill="#8eaa94"/><circle cx="${c.x+51}" cy="${c.y+16+i*14}" r="3" fill="#b7caaa"/>`).join('');
 const label=['sensor','igniter','pressure'].includes(c.id)?`<text x="${c.x+c.w/2}" y="${c.y+c.h+13}" text-anchor="middle">${c.id==='sensor'?'FLAME SENSOR':c.id.toUpperCase()}</text>`:`<text x="${c.x+c.w/2}" y="${c.y+c.h-6}" text-anchor="middle">${c.id==='burners'?'BURNER ASSEMBLY':c.id==='gas'?'GAS VALVE':c.id==='vent'?'EXHAUST':c.id.toUpperCase()}</text>`;
 return `<g class="component ${componentStatus(c).toLowerCase()} ${state.selected===c.id?'selected':''}" data-component="${c.id}" tabindex="0" role="button" aria-label="${c.name}, ${componentStatus(c)}"><title>${c.name} · ${componentStatus(c)}</title><rect class="shape" x="${c.x}" y="${c.y}" width="${c.w}" height="${c.h}" rx="${c.id==='pressure'?28:6}"/>${detail}${label}</g>`;
 }).join('');
 $('#diagramStage').innerHTML=`<svg viewBox="0 0 520 590" aria-label="Conceptual furnace schematic based on supplied references"><defs><pattern id="grille" width="7" height="7" patternUnits="userSpaceOnUse"><path d="M0 3h7" stroke="#c9d5cd" stroke-width="2"/></pattern></defs><text x="25" y="30" font-size="10" fill="#80948a" font-family="monospace">FRONT VIEW / SERVICE PANEL REMOVED</text><rect x="126" y="51" width="315" height="504" rx="8" fill="#edf2ee" stroke="#8ca398" stroke-width="2"/><rect x="138" y="66" width="291" height="32" fill="url(#grille)"/><path d="M133 413h301" stroke="#a4b6aa" stroke-width="2"/><path d="M110 71V40h142v25M285 237V215H194v-26M312 264h76v29M375 251v155l10 13M242 401v20h140" fill="none" stroke="#8caa96" stroke-width="3" stroke-linejoin="round"/><text x="25" y="567" font-size="9" fill="#80948a" font-family="monospace">CONCEPTUAL LAYOUT · NOT A SERVICE DRAWING</text>${shapes}<text x="452" y="126" font-size="9" fill="#a5b3aa" transform="rotate(90 452 126)">COMBUSTION COMPARTMENT</text><text x="452" y="430" font-size="9" fill="#a5b3aa" transform="rotate(90 452 430)">AIR HANDLING</text></svg>`;
 document.querySelectorAll('[data-component]').forEach(el=>{const select=()=>{state.selected=el.dataset.component;renderDiagram();renderComponent()};el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}}});
}
function renderComponent(){const c=profile.components.find(c=>c.id===state.selected);const count=state.evidence.filter(e=>e.component.toLowerCase().includes(c.id==='sensor'?'flame':c.name.toLowerCase())).length;
 $('#componentPane').innerHTML=`<header><h3>${c.name}</h3><span class="tag ${c.id==='sensor'&&!state.restored?'amber':''}">${({UNKNOWN:'NOT CHECKED',SUSPECTED:'SUSPECT',TESTING:'CHECK IN PROGRESS',FAILED:'DAMAGE REPORTED',CORRECTED:'SERVICED',VALIDATED:'OPERATION VERIFIED'})[componentStatus(c)]}</span></header><small>REFERENCE ${escapeHTML(c.key)}</small><p><b>Normal function</b> ${escapeHTML(c.expected)}</p><p><b>Service findings</b> ${escapeHTML(observed(c))}</p><small>${count} related service log entries · operating readings still required</small>`;
}
function renderReasoning(){
 $('#reasonTitle').textContent=state.restored?'Post-service operational check':state.step!==null?'Guided technician procedure':'Troubleshooting the shutdown';$('#reasonBadge').textContent=state.restored?'OPERATION VERIFIED':state.step!==null?'TESTING':'INVESTIGATING';
 if(state.restored){$('#reasoning').innerHTML=`<div class="success"><div class="eyebrow">OPERATIONAL CHECK / TECHNICIAN REPORTED</div><h3>Normal heating operation reported.</h3><p>The furnace remains running during the observed retest. The reported shutdown complaint is resolved for this demo service call.</p><ul><li>Sensor inspection documented</li><li>${state.correctiveActions.length?'Cleaning and reinstallation recorded':'Inspection and reinstallation recorded; no cleaning confirmed'}</li><li>Continued operation reported on retest</li></ul></div><div class="state-comparison"><div class="state-card expected"><div class="eyebrow">NORMAL OPERATION</div><p>Heating cycle continues with a call for heat.</p></div><div class="state-card expected"><div class="eyebrow">SERVICE FINDINGS</div><p>Continued operation reported.</p></div></div><p class="footnote">96% is a simulated normal-operation match score. Flame signal, full-cycle timing, and remaining equipment functions are unmeasured. The result does not prove a unique root cause.</p><button id="reportBtn">Review operational check results ↗</button>`;$('#reportBtn').onclick=()=>openDrawer('evidence');return}
 if(state.step!==null){renderProcedure();return}
 $('#reasoning').innerHTML=`<div class="state-comparison"><div class="state-card"><div class="eyebrow">REPORTED SYMPTOM</div><p>Burners reportedly ignite, then operation terminates.</p></div><div class="state-card expected"><div class="eyebrow">NORMAL OPERATION</div><p>Flame remains established while a call for heat continues.</p></div></div><div class="discrepancy"><strong>OPERATING FAULT</strong>Burners light, but the heating cycle does not continue.</div><div class="eyebrow">POSSIBLE CAUSES <span>CHECKS REQUIRED</span></div><div class="hypotheses">${profile.hypotheses.map((h,i)=>`<div class="hypothesis" title="${escapeHTML(h.support)}"><i>0${i+1}</i><span>${h.name}</span><span class="bar" style="--fill:${[85,50,25][i]}%"></span><span>${h.relevance} priority</span></div>`).join('')}</div><div class="next-test"><div class="eyebrow">RECOMMENDED NEXT TEST</div><h3>${state.paused?'Continue diagnostic checks':'Inspect the flame sensor'}</h3><p>${state.paused?escapeHTML(state.paused):'Burners lighting and then shutting down warrants a flame-sensing circuit check. Inspect the sensor first; the symptom alone does not confirm a bad sensor.'}</p><button class="primary" id="beginTest">${state.paused?'Revisit guided inspection':'Begin guided inspection →'}</button></div><p class="footnote">Grounded in parts key 19 and technician observation EV-004. Diagnostic ranking is simulated; flame-signal reading has not been measured.</p>`;$('#beginTest').onclick=beginTest;
}
function beginTest(){state.step=0;state.paused=null;state.stage=6;state.sensorState='TESTING';state.selected='sensor';view='schematic';state.tests.push({type:'Flame sensor inspection',status:'In progress',started:now()});addEvidence('Guided test','Flame sensor','Technician began a guided inspection. Power isolation has not yet been confirmed.','Procedure event');render();toast('Inspection opened · confirm isolation before access')}
function renderProcedure(){
 const s=profile.procedure[state.step];
 $('#reasoning').innerHTML=`<div class="procedure"><div class="procedure-progress">${profile.procedure.map((_,i)=>`<span class="${i<=state.step?'done':''}"></span>`).join('')}</div><div class="eyebrow">STEP ${state.step+1} OF 7 / FLAME SENSOR INSPECTION</div><h3>${s.title}</h3><p>${s.text}</p>${s.image?`<img src="${asset(profile.photos[s.image])}" alt="Supplied flame sensor inspection reference"><small class="footnote">Supplied screenshot · service reference</small>`:''}${state.step===3?`<div class="choices"><button data-inspect="Clean">Clean</button><button data-inspect="Appears clean">Appears clean</button><button data-inspect="Damaged">Damaged</button><button data-inspect="Cannot determine">Cannot determine</button></div>`:state.step===6?`<div class="choices"><button class="primary" id="passBtn">Furnace remains running</button><button id="failBtn">Failure persists</button></div>`:`<button class="primary" id="nextStep">${s.button} →</button>`}<p class="footnote">This front-end demo records confirmations; it cannot verify physical isolation or perform tests. Follow manufacturer instructions.</p></div>`;
 if(state.step===3)document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>inspect(b.dataset.inspect));
 else if(state.step===6){$('#passBtn').onclick=()=>retest(true);$('#failBtn').onclick=()=>retest(false)}
 else $('#nextStep').onclick=()=>{addEvidence('Procedure confirmation','Flame sensor',s.button,'Technician confirmation');state.step++;if(state.step===5)state.stage=8;render();toast('Confirmation recorded')};
}
function inspect(result){
 state.inspection=result;state.score=79;addEvidence('Physical inspection','Flame sensor',`Inspection result: ${result}.`);
 if(result==='Clean'){state.correctiveActions.push({component:'sensor',action:'Cleaning performed',timestamp:now()});state.sensorState='CORRECTED';state.stage=7;addEvidence('Corrective action','Flame sensor','Technician confirms cleaning performed using an appropriate service method. Reinstallation and retest still required.','Technician action report');state.step=4}
 else if(result==='Appears clean'){state.sensorState='TESTING';state.stage=7;state.step=4}
 else{state.sensorState=result==='Damaged'?'FAILED':'UNKNOWN';state.step=null;state.stage=4;state.paused=result==='Damaged'?'Damage was reported. Do not proceed with a cleaning-based restoration. Use manufacturer guidance to confirm the appropriate replacement and record additional service findings.':'Sensor condition could not be determined. Record a clearer inspection image or a manufacturer-specified diagnostic measurement before selecting a corrective action.';state.tests.at(-1).status='Inconclusive / further service required'}
 render();toast('Inspection recorded · normal-operation match 79%');
}
function retest(pass){
 addEvidence('Operational retest','Flame proving system',pass?'Technician reports furnace remains running during the observed heating cycle.':'Technician reports failure persists after the inspection / corrective action.','Direct technician observation');
 state.tests.at(-1).status=pass?'Reported operation restored':'Failure persists';state.validationResults.push({passed:pass,timestamp:now(),scope:'Reported sustained operation; remaining values unmeasured'});state.step=null;
 if(pass){state.restored=true;state.score=96;state.stage=9;state.sensorState='VALIDATED';state.paused=null}else{state.restored=false;state.score=71;state.stage=4;state.sensorState='SUSPECTED';state.paused='The retest did not restore operation. Cleaning did not resolve the complaint. Record flame-signal measurement, control fault indication, or combustion observations using manufacturer guidance. Previous service findings remain in the log.'}
 render();toast(pass?'Operational check recorded · heating continues':'Failure retained · diagnosis reopened');
}
function renderSequence(){
 $('#sequence').innerHTML=profile.sequence.map((s,i)=>`<div class="seq ${!state.restored&&i===6?'diverged':''}" data-seq="${i}"><b>${String(i+1).padStart(2,'0')}</b>${s}</div>`).join('');
 $('#comparison').innerHTML=`<div><b>NORMAL</b>Burners ignite → Flame proven → Heating cycle continues</div><div class="${state.restored?'':'observed'}"><b>ACTUAL</b>${state.restored?'Burners ignite → Continued operation reported':'Burners ignite → Shutdown; flame-proof status unknown'}</div><div class="footnote">The reported fault is shutdown after ignition. A flame-sensing circuit fault is still a possible cause.</div>`;
}
function runSequence(){clearInterval(sequenceTimer);renderSequence();const button=$('#sequenceBtn');button.disabled=true;button.textContent='Sequence running…';let i=0;sequenceTimer=setInterval(()=>{const el=$(`[data-seq="${i}"]`);if(el)el.classList.add('running');i++;if(i>=profile.sequence.length){clearInterval(sequenceTimer);button.disabled=false;button.textContent='▷ Run normal sequence';if(!state.restored)$('[data-seq="6"]').classList.remove('running');toast('Normal sequence complete · compare where the heating cycle stops')}},480)}
function renderInput(){
 document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
 let fields='';
 if(mode==='photo'||mode==='audio')fields=`<label for="uploadFile">${mode==='photo'?'Upload an equipment photograph':'Upload an audio recording'}</label><input id="uploadFile" type="file" accept="${mode==='photo'?'image/*':'audio/*'}" required><label for="entry">What service finding does this file document?</label><textarea id="entry" placeholder="Describe the observation; files are stored in memory for this session."></textarea>`;
 else if(mode==='measurement')fields='<label for="measurementName">Measurement / test point</label><input id="measurementName" type="text" placeholder="e.g. Flame signal" required><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><label for="value">Reading</label><input id="value" type="number" step="any" required></div><div><label for="unit">Units</label><input id="unit" type="text" placeholder="Specify units" required></div></div><label for="entry">Conditions / context</label><textarea id="entry" placeholder="Record test conditions. No manufacturer threshold is provided in this demo."></textarea>';
 else if(mode==='test')fields='<label for="entry">Record a diagnostic test result</label><textarea id="entry" required placeholder="Name the test, conditions, and observed result."></textarea><button type="button" id="guidedTestBtn" style="margin-top:10px">Open guided flame sensor inspection →</button>';
 else if(mode==='voice')fields='<label for="entry">Voice note transcript (simulated)</label><textarea id="entry" required placeholder="Type a voice-note transcript here. This demo does not access the microphone."></textarea>';
 else fields='<label for="entry">Describe an observation</label><textarea id="entry" required placeholder="Furnace lights, runs for approximately five seconds, and then shuts down."></textarea>';
 fields+='<label for="association">Associate with component</label><select id="association"><option>Flame proving system</option>'+profile.components.map(c=>`<option>${c.name}</option>`).join('')+'</select>';
 $('#inputFields').innerHTML=fields;if($('#guidedTestBtn'))$('#guidedTestBtn').onclick=beginTest;
 $('#inputHint').textContent=mode==='voice'?'Voice input is simulated with a typed transcript.':mode==='audio'?'Upload supported · audio analysis is simulated.':'Service findings stay in the log as troubleshooting continues.';
}
function submitEvidence(event){event.preventDefault();let text=$('#entry').value.trim(),extra={},source={observation:'Technician observation',photo:'Photo upload',audio:'Audio upload',voice:'Simulated voice transcript',measurement:'Diagnostic measurement',test:'Diagnostic test result'}[mode];
 if(mode==='photo'||mode==='audio'){const file=$('#uploadFile').files[0];if(!file)return;extra={fileName:file.name,[mode==='photo'?'imageURL':'audioURL']:URL.createObjectURL(file)};text=text||`Uploaded ${file.name}. No automated interpretation performed.`;extra.confidence='File supplied; content not analyzed'}
 if(mode==='measurement')text=`${$('#measurementName').value.trim()}: ${$('#value').value} ${$('#unit').value.trim()}. ${text} Manufacturer threshold unknown; measurement not classified automatically.`;
 const item=addEvidence(source,$('#association').value,text,extra.confidence||'Technician report; unverified',extra);state.observations.push(item);if(mode==='test')state.tests.push({type:'Technician-entered test',result:text,status:'Recorded'});render();renderInput();toast(`${item.id} · Service finding recorded${mode==='photo'||mode==='audio'?' · analysis simulated':''}`);
}
function renderEvidence(){return `<p class="footnote">Service-call log. Uploaded files remain in browser memory until reset or reload. Previous findings remain when the suspected cause changes.</p>${state.evidence.slice().reverse().map(e=>`<article class="evidence-card"><header><b>${e.id}</b><span>${e.timestamp}</span></header><p>${escapeHTML(e.observation)}</p><small>SOURCE ${escapeHTML(e.source)} · ${escapeHTML(e.provenance)}</small><small>COMPONENT ${escapeHTML(e.component)}</small><small>BASIS ${escapeHTML(e.confidence)}</small>${e.link?`<p><a href="${asset(e.link)}" target="_blank" rel="noopener">Open supplied parts documentation ↗</a></p>`:''}${e.image||e.imageURL?`<img src="${e.imageURL||asset(e.image)}" alt="${escapeHTML(e.source)}">`:''}${e.audioURL?`<audio controls src="${e.audioURL}"></audio>`:''}</article>`).join('')}`}
function renderAgent(){
 const operations=[
 ['Equipment identification','DOCUMENT-BACKED',`${profile.model} retrieved from the supplied equipment document. Physical label still requires technician confirmation.`,'EV-001'],
 ['Equipment documentation retrieval','REFERENCE AVAILABLE','Parts diagram and parts listing are available in the supplied PDF.','EV-001'],
 ['Parts lookup','DOCUMENT-BACKED','Key 19 identifies R44745-001 SENSOR-FLAME; Part Number column: 98M87. PDF page 3 / printed page 2.','EV-002'],
 ['Image comparison','SIMULATED','Supplied screenshots support component-location references. Uploaded images are displayed, but no vision model analyzes them.','EV-003'],
 ['Audio analysis','SIMULATED / NOT ANALYZED','Uploaded audio can be replayed. No noise diagnosis or transcription is performed.','Uploaded service recordings, if supplied'],
 ['Observation matched','RULE DEMONSTRATION','Seeded complaint reports ignition followed by shutdown. This pattern makes flame proving relevant without proving its cause.','EV-004'],
 ['Diagnostic rule evaluation','SIMULATED',state.paused||'Check the flame-sensing circuit first; burner flame loss and control or safety circuit interruption remain other possible causes.','Complaint and inspection findings'],
 ['Equipment-state comparison',state.restored?'RETEST REPORTED':'OPERATING FAULT',state.restored?'Expected continued heating compared with technician-reported continued operation. Full safety and performance verification remain outside this demo.':'Expected continued flame during a call for heat compared with reported shutdown; flame signal is unmeasured.','Technician observation / operational retest'],
 ['Checks still needed',state.inspection?'INSPECTION RECORDED':'OPEN',state.inspection?`Sensor inspection: ${state.inspection}. Actual flame signal and other manufacturer criteria still require measurement.`:'Sensor condition unknown. Electrical flame-proving performance has not been measured.','Current session record'],
 ['Agent action','PROCEDURE REQUEST',state.restored?'Record post-service operational check and retain the service-call log.':state.paused?'Request more service findings before closing the shutdown complaint.':'Request technician inspection of the flame sensor, with power isolation and reassembly confirmations.','Guided inspection workflow']
 ];return '<p class="footnote">Inspectable sources, operations, and state changes. No hidden chain-of-thought is shown. Tool cards distinguish document-backed references from simulated evaluation.</p>'+operations.map(([name,status,description,refs])=>`<article class="operation"><span class="tag">${status}</span><h3>${name}</h3><p>${escapeHTML(description)}</p><small>SUPPORT ${escapeHTML(refs)}</small>${name==='Parts lookup'||name==='Equipment documentation retrieval'?`<p><a href="${asset(profile.documentation)}" target="_blank" rel="noopener">Inspect source document ↗</a></p>`:''}</article>`).join('');
}
function openDrawer(type){$('#drawerEyebrow').textContent=type==='agent'?'AI ASSIST / SOURCES AND CHECKS':'SERVICE CALL / FINDINGS LOG';$('#drawerTitle').textContent=type==='agent'?'Behind the recommendation':`${state.evidence.length} service log entries`;$('#drawerContent').innerHTML=type==='agent'?renderAgent():renderEvidence();$('#drawer').showModal()}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
$('#evidenceForm').onsubmit=submitEvidence;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderInput()});$('#agentBtn').onclick=()=>openDrawer('agent');$('#evidenceBtn').onclick=()=>openDrawer('evidence');$('#closeDrawer').onclick=()=>$('#drawer').close();$('#drawer').onclick=e=>{if(e.target===$('#drawer')&&e.clientX<$('#drawer').getBoundingClientRect().left)$('#drawer').close()};$('#resetBtn').onclick=()=>{if(confirm('Reset this demo session? Uploaded files and session evidence will be cleared.')){state.evidence.forEach(e=>{if(e.imageURL)URL.revokeObjectURL(e.imageURL);if(e.audioURL)URL.revokeObjectURL(e.audioURL)});reset();$('#sequenceBtn').disabled=false;$('#sequenceBtn').textContent='▷ Run normal sequence';toast('Demo session reset')}};$('#sequenceBtn').onclick=runSequence;$('#photoBtn').onclick=()=>{view='photo';renderDiagram()};$('#schematicBtn').onclick=()=>{view='schematic';renderDiagram()};reset();
