/* Explanation of intended service-call support; no connected AI claims. */
window.openHVACDifference=function(){
 const drawer=document.getElementById('drawer');
 document.getElementById('drawerEyebrow').textContent='WHY THIS IS DIFFERENT / AN HVAC SERVICE PERSPECTIVE';
 document.getElementById('drawerTitle').textContent='You already have computerized diagnostics.';
 document.getElementById('drawerContent').innerHTML=`
 <section class="difference-intro"><h3>“We already have fault codes, service apps, and connected diagnostics.”</h3><p>That is a fair response. Those tools can be very useful. An OEM tool may already show live readings, fault history, guided checks, or remote monitoring. The useful question is: <strong>does it help you carry the whole service call from complaint to a verified repair?</strong></p><p>The aim here is to connect the unit’s normal sequence of operation with your actual findings, keep track of what has been checked, and update the next check as the job develops.</p></section>
 <section class="difference-case"><h3>Take this furnace complaint: burners light, then shut down.</h3><p>A flame-related code or a short burner cycle can point you toward the flame-sensing circuit. You still need to decide what to check. The sensor, connection, grounding, burner flame, and control or safety circuit may need attention under the manufacturer’s procedure.</p><p>In this approach, the service call keeps that distinction visible: <strong>what the customer reported, what you actually saw, what you measured, and what is still unconfirmed.</strong> Cleaning the sensor records service work. It does not close the call. A post-service operational check must be recorded; if the shutdown continues, the earlier findings stay available and troubleshooting continues.</p><p>This demo shows that workflow. It does not prove a flame-signal fault or measure a flame signal.</p></section>
 <section class="difference-section"><h3>Where the extra support could earn its place</h3><ul class="difference-list">
 <li><strong>A code points to a circuit, but the cause is still unclear.</strong> Keep possible causes and the checks needed to separate them visible, instead of treating a code as a parts replacement instruction.</li>
 <li><strong>The complaint is intermittent—or the unit runs when you arrive.</strong> Keep customer descriptions, photos, fault history, and test conditions together. A “could not duplicate” visit can leave a useful record of what happened and what was actually checked.</li>
 <li><strong>The readings are in one tool and the service notes are somewhere else.</strong> Tie each reading or finding to the part or circuit and the operating condition it describes. A reading without test conditions can be hard to use on the next visit.</li>
 <li><strong>Several checks or service actions have already been tried.</strong> Retain the results, including unsuccessful work, so the next recommendation takes account of what has already been done.</li>
 <li><strong>Another technician takes over, or you get a callback.</strong> Leave a service-call history that explains the complaint, checks, service performed, and operational check—not just “cleaned sensor.”</li>
 <li><strong>The fault does not fit a familiar troubleshooting branch.</strong> Organize findings across the heating sequence and related circuits. Where the facts do not support a conclusion, request another check rather than force a diagnosis.</li>
 </ul></section>
 <section class="difference-section"><h3>Your doubt is a useful check.</h3><p>If your current diagnostic platform already does these things well, some of this will overlap. The value has to be demonstrated in fewer repeated checks, better handoffs, clearer service records, and more reliably confirmed repairs. A different screen or an AI label alone does not establish that value.</p><p>Your experience still matters: selecting the right test point, recognizing an unsafe condition, checking the manufacturer’s procedure, and judging whether a reading makes sense. Assistance should make those findings easier to use and review.</p></section>
 <section class="difference-section"><h3>The broader service implication</h3><p>A connected implementation could help turn each service call into a usable troubleshooting history, support technicians across different equipment models, and make complex or repeat calls easier to pick up. The same approach could support other equipment with a defined sequence of operation. It would require reliable service information, correctly identified equipment, suitable data connections, and field testing to show that it improves outcomes.</p></section>
 <div class="difference-note"><strong>What is working here:</strong> component references, technician-entered findings, a service log, guided inspection, and recorded operational checks.<br><br><strong>What is simulated:</strong> AI recommendations, diagnostic priority, and the normal-operation match score. This prototype has no live equipment connection, automated photo/audio interpretation, or persistent service history. It does not replace OEM diagnostics or manufacturer service procedures.</div>
 <button class="primary difference-return" id="differenceReturn">Return to the service call →</button>`;
 document.getElementById('differenceReturn').onclick=()=>drawer.close();
 if(!drawer.open)drawer.showModal();drawer.scrollTop=0;
};
document.getElementById('differenceBtn').onclick=window.openHVACDifference;
