/* Interface orientation: no diagnostic or equipment state is changed. */
(()=>{
 const storageKey='fieldwork.interface-tour.v1';
 const steps=[
 {target:'.identity h1',title:'Start with the equipment model.',text:'Use the same service approach you already know: confirm the unit, review the sequence of operation, check the complaint, take readings, make the repair, and verify operation. Check this model against the furnace nameplate.',color:'#ffca28',label:'CONFIRM THE UNIT'},
 {target:'.health',title:'Compare with normal operation.',text:'The normal-operation reference shows how this furnace should be configured and how the heating cycle should run. The percentage is a demo progress indicator. It is not an efficiency rating, a safety check, or a measured furnace reading.',color:'#ff5c96',label:'NORMAL OPERATION REFERENCE'},
 {target:'.equipment-panel .panel-head',secondary:'[data-component="sensor"]',title:'Select the component you are checking.',text:'Select a part on the furnace schematic to review its normal function, service findings, and related log entries. Amber identifies a suspect component. The flame sensor still needs checking before you call it a bad part. This layout is a service reference, not a manufacturer wiring diagram.',color:'#19d9df',label:'FURNACE COMPONENTS'},
 {target:'#componentPane',title:'Review the component check status.',text:'NOT CHECKED means no check is recorded. SUSPECT means the part or circuit needs diagnosis. SERVICED means work has been recorded. OPERATION VERIFIED means the technician has reported a successful operational check after service.',color:'#b5f143',label:'COMPONENT CHECK STATUS'},
 {target:'.input-panel .panel-head',secondary:'#inputTools',title:'Record your service findings.',text:'Enter symptoms, inspection notes, photos, meter readings, and test results. Select the part or circuit you checked. Audio files and typed voice notes can be added to this demo, but recordings and photos are not automatically interpreted.',color:'#ffca28',label:'NOTES, READINGS, AND TEST RESULTS'},
 {target:'.reasoning-panel .panel-head',secondary:'.next-test',title:'Work through the possible causes.',text:'Compare the reported symptom with normal operation, review possible causes, and choose the next diagnostic check. Begin guided inspection walks through power isolation, inspection, service, and an operational check. If the complaint remains, troubleshooting continues.',color:'#ff5c96',label:'DIAGNOSTIC CHECKS'},
 {target:'.twin-panel summary',secondary:'#comparison',title:'Check the sequence of operation.',text:'Run the normal heating sequence and compare it with the actual complaint. Here, the burners light, then the furnace shuts down. Check the flame-sensing circuit as a possible cause; a loss of flame signal has not been confirmed by a reading.',color:'#19d9df',label:'WHERE DOES THE HEATING CYCLE STOP?'},
 {target:'#evidenceBtn',title:'Review the service-call log.',text:'The service log keeps your notes, readings, test results, timestamps, and parts references together. Previous findings remain when the suspected cause changes. This demo clears the service-call log when you reset or reload.',color:'#b5f143',label:'SERVICE HISTORY FOR THIS CALL'},
 {target:'#agentBtn',title:'Check the basis for the recommendation.',text:'View agent work shows the service documents and parts references used, the reported symptoms, and checks still needed. The AI-assisted recommendations are simulated in this demo. Use your readings and manufacturer service information to confirm the diagnosis.',color:'#ffca28',label:'SERVICE REFERENCES AND CHECKS'},
 {target:'#differenceBtn',title:'Why is this different?',text:'You already have fault codes, diagnostic apps, and manufacturer service tools. The added value here is keeping the whole service call together: the complaint, sequence of operation, your readings, what has been ruled out, and whether the repair resolved the complaint. Open the explanation for the practical differences—and the limits. Replay this walkthrough anytime with Tour.',color:'#ff5c96',label:'A FAIR QUESTION FROM AN HVAC TECHNICIAN'}
 ];
 const button=document.getElementById('tourBtn');
 const layer=document.createElement('div');layer.id='userTour';layer.hidden=true;layer.setAttribute('role','dialog');layer.setAttribute('aria-modal','true');layer.setAttribute('aria-labelledby','tourTitle');
 layer.innerHTML='<div class="tour-shade"></div><svg id="tourInk" aria-hidden="true"></svg><section class="tour-card"><div class="tour-meta"><span id="tourLabel"></span><button id="tourClose" aria-label="Close tour">✕</button></div><div id="tourCount"></div><h2 id="tourTitle"></h2><p id="tourText"></p><div class="tour-reminder">↻ Replay anytime with the <strong>Tour</strong> button up top.</div><button id="tourDifference" hidden>Why is this different? →</button><div class="tour-controls"><button id="tourBack">← Back</button><button id="tourSkip">Skip tour</button><button id="tourNext">Next →</button></div></section>';
 document.body.append(layer);
 let index=0,active=false,frame,priorFocus,priorScroll=0;
 const get=id=>document.getElementById(id);
 function seen(){try{return localStorage.getItem(storageKey)==='seen'}catch{return false}}
 function remember(){try{localStorage.setItem(storageKey,'seen')}catch{/* Tour remains replayable if browser storage is unavailable. */}}
 function circle(rect,color){const x=rect.left-10,y=rect.top-10,w=rect.width+20,h=rect.height+20,cx=x+w/2,cy=y+h/2;return `<path class="tour-draw" d="M ${x+w*.12} ${y+h*.19} C ${x+w*.4} ${y-9}, ${x+w*.93} ${y-5}, ${x+w} ${cy} C ${x+w+8} ${y+h*.91}, ${x+w*.69} ${y+h+9}, ${cx} ${y+h+5} C ${x+w*.07} ${y+h+4}, ${x-12} ${y+h*.76}, ${x-3} ${cy} C ${x-4} ${y+h*.21}, ${x+w*.21} ${y-9}, ${x+w*.6} ${y+1}" stroke="${color}"/><path class="tour-sketch" d="M ${x+w*.15} ${y+h*.15} C ${x+w*.55} ${y-7}, ${x+w+6} ${y+h*.05}, ${x+w+3} ${cy} C ${x+w} ${y+h+8}, ${x+w*.25} ${y+h+12}, ${x+w*.04} ${y+h*.71}" stroke="${color}"/>`}
 function arrow(from,to,color){const dx=to.x-from.x,dy=to.y-from.y,length=Math.hypot(dx,dy)||1,ux=dx/length,uy=dy/length;const bend=25;const ax=to.x-ux*20+uy*10,ay=to.y-uy*20-ux*10,bx=to.x-ux*20-uy*10,by=to.y-uy*20+ux*10;return `<path class="tour-draw tour-arrow" d="M ${from.x} ${from.y} Q ${(from.x+to.x)/2+uy*bend} ${(from.y+to.y)/2-ux*bend} ${to.x} ${to.y} M ${ax} ${ay} L ${to.x} ${to.y} L ${bx} ${by}" stroke="${color}"/>`}
 function draw(){if(!active)return;const step=steps[index],target=document.querySelector(step.target);if(!target)return;const r=target.getBoundingClientRect(),card=layer.querySelector('.tour-card').getBoundingClientRect();const ink=get('tourInk');ink.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`);let markup=circle(r,step.color);const end={x:Math.min(Math.max(card.left+30,r.left+12),r.right-4),y:r.bottom+15};const start={x:card.left+35,y:r.top>card.bottom?card.bottom+8:card.top-8};if(Math.hypot(end.x-start.x,end.y-start.y)>35)markup+=arrow(start,end,step.color);if(step.secondary){const secondary=document.querySelector(step.secondary);if(secondary){const q=secondary.getBoundingClientRect();if(q.top>=0&&q.bottom<card.top-16)markup+=circle(q,step.color)}}ink.innerHTML=markup}
 function show(){const step=steps[index];get('tourLabel').textContent=step.label;get('tourCount').textContent=`QUICK ORIENTATION · ${index+1} / ${steps.length}`;get('tourTitle').textContent=step.title;get('tourText').textContent=step.text;get('tourNext').textContent=index===steps.length-1?'Finish tour ✓':'Next →';get('tourDifference').hidden=index!==steps.length-1;get('tourBack').disabled=index===0;layer.style.setProperty('--tour-color',step.color);const target=document.querySelector(step.target);if(target){if(target.closest('details'))target.closest('details').open=true;const r=target.getBoundingClientRect();window.scrollTo({top:Math.max(0,scrollY+r.top-Math.min(140,innerHeight*.15)),behavior:'instant'})}const card=layer.querySelector('.tour-card');card.style.top='';card.style.bottom='';const tr=target?.getBoundingClientRect(),cr=card.getBoundingClientRect();if(tr&&tr.bottom>cr.top-20&&tr.top<cr.bottom){card.style.top='20px';card.style.bottom='auto'}cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);get('tourNext').focus({preventScroll:true})}
 function open(){if(active)return;if(document.getElementById('drawer').open)document.getElementById('drawer').close();priorFocus=document.activeElement;priorScroll=scrollY;active=true;index=0;layer.hidden=false;document.querySelector('main').inert=true;document.querySelector('.topbar').inert=true;document.body.classList.add('tour-open');show()}
 function close(){if(!active)return;active=false;remember();layer.hidden=true;document.querySelector('main').inert=false;document.querySelector('.topbar').inert=false;document.body.classList.remove('tour-open');window.scrollTo({top:priorScroll,behavior:'instant'});(priorFocus instanceof HTMLElement?priorFocus:button).focus({preventScroll:true})}
 get('tourDifference').onclick=()=>{close();window.openHVACDifference()};button.onclick=open;get('tourClose').onclick=close;get('tourSkip').onclick=close;get('tourBack').onclick=()=>{if(index>0){index--;show()}};get('tourNext').onclick=()=>{if(index===steps.length-1)close();else{index++;show()}};
 window.addEventListener('resize',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)});window.addEventListener('scroll',()=>{if(active){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}},{passive:true});
 layer.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const controls=[...layer.querySelectorAll('button:not(:disabled):not([hidden])')];const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 if(!seen())setTimeout(open,500);
})();
