'use client';
import { useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';

type Item={id:number;name:string;type:string;color:string;content:string;meta:string};
type ScoreAlert={id:string;text:string};
type Config={items:Item[];speed:number;brightness:number;advanceMode:'time'|'complete';intervalSeconds:number;powered:boolean;showGif?:boolean;detectorOn?:boolean;revision?:number};
const fallback:Config={items:[{id:1,name:'Ticker',type:'Message',color:'#baff3c',content:'SIGNAL TICKER  •  LIVE DISPLAY',meta:''}],speed:5,brightness:82,advanceMode:'complete',intervalSeconds:20,powered:true};

function Matrix({text,color,speed,brightness,onComplete}:{text:string;color:string;speed:number;brightness:number;onComplete:()=>void}){
 const ref=useRef<HTMLCanvasElement>(null),offset=useRef(0),done=useRef(onComplete),liveContent=useRef({text,color});done.current=onComplete;liveContent.current={text,color};
 useEffect(()=>{const c=ref.current,x=c?.getContext('2d');if(!c||!x)return;offset.current=0;let frame=0,last=performance.now();const draw=(now:number)=>{const w=innerWidth,h=innerHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}x.setTransform(d,0,0,d,0,0);x.fillStyle='#020403';x.fillRect(0,0,w,h);offset.current-=(now-last)*(.015+speed*.011);last=now;const v=document.createElement('canvas');v.width=w;v.height=h;const q=v.getContext('2d')!,live=liveContent.current,plain=live.text.replace(/\[\[#[0-9a-f]{6}\]\]/gi,'');q.fillStyle='#000';q.fillRect(0,0,w,h);q.textBaseline='middle';q.font=`800 ${Math.max(25,h*.38)}px ui-monospace,Menlo,monospace`;const tw=q.measureText(plain).width+160;if(offset.current<-(tw+w)){offset.current=0;done.current()}let cursor=w+offset.current,ink=live.color;for(const part of live.text.split(/(\[\[#[0-9a-f]{6}\]\])/gi)){const tag=part.match(/^\[\[(#[0-9a-f]{6})\]\]$/i);if(tag){ink=tag[1];continue}q.fillStyle=ink;q.shadowColor=ink;q.shadowBlur=8;q.fillText(part,cursor,h/2);cursor+=q.measureText(part).width}const data=q.getImageData(0,0,w,h).data,s=Math.max(2.2,Math.min(4.5,w/245)),p=s*1.72;x.globalAlpha=.45+brightness/180;for(let yy=p/2;yy<h;yy+=p)for(let xx=p/2;xx<w;xx+=p){const i=((yy|0)*w+(xx|0))*4,r=data[i],g=data[i+1],b=data[i+2];x.beginPath();x.arc(xx,yy,s/2,0,Math.PI*2);if(r+g+b>25){x.shadowColor=`rgb(${r},${g},${b})`;x.shadowBlur=s*2;x.fillStyle=`rgb(${r},${g},${b})`}else{x.shadowBlur=0;x.fillStyle='#18201b'}x.fill()}x.globalAlpha=1;x.shadowBlur=0;frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);return()=>cancelAnimationFrame(frame)},[speed,brightness]);return <canvas ref={ref}/>;
}
function AlertDisplay({alert,config,onComplete}:{alert:ScoreAlert;config:Config;onComplete:()=>void}){const[ready,setReady]=useState(false);useEffect(()=>{setReady(false);const id=setTimeout(()=>setReady(true),1800);return()=>clearTimeout(id)},[alert.id]);return ready?<Matrix text={alert.text} color="#ff3b3b" speed={config.speed} brightness={config.brightness} onComplete={onComplete}/>:<div className="score-alert-flash">SCORE ALERT</div>}

export default function Ticker(){const[config,setConfig]=useState<Config>(fallback),[active,setActive]=useState(0),[alert,setAlert]=useState<ScoreAlert|null>(null),queue=useRef<ScoreAlert[]>([]),alertRef=useRef<ScoreAlert|null>(null);useEffect(()=>{const read=()=>{try{const value=localStorage.getItem('signal-popout');if(value){setConfig(JSON.parse(value));setActive(0)}}catch{}},receive=(event:StorageEvent)=>{if(!event.newValue)return;try{if(event.key==='signal-score-alert'){const next=JSON.parse(event.newValue);if(alertRef.current)queue.current.push(next);else{alertRef.current=next;setAlert(next)}}else if(event.key==='signal-live-items'){const live=JSON.parse(event.newValue);setConfig(current=>({...current,items:current.items.map(item=>{const fresh=live.items.find((candidate:Item)=>candidate.id===item.id)||live.items.find((candidate:Item)=>candidate.type===item.type);return fresh?{...item,content:fresh.content,meta:fresh.meta}:item})}))}}catch{}};read();addEventListener('storage',read);addEventListener('storage',receive);return()=>{removeEventListener('storage',read);removeEventListener('storage',receive)}},[]);useEffect(()=>{if(config.advanceMode!=='time'||!config.powered||config.showGif||alert||config.items.length<2)return;const id=setInterval(()=>setActive(v=>(v+1)%config.items.length),config.intervalSeconds*1000);return()=>clearInterval(id)},[config,alert]);const finishAlert=()=>{const next=queue.current.shift()||null;alertRef.current=next;setAlert(next)},count=Math.max(config.items.length,1),step=(direction:number)=>setActive(v=>(v+direction+count)%count),item=config.items[active%count]||fallback.items[0];return <div className="popout-page"><div className="popout-shell"><i className="pop-screw ps1"/><i className="pop-screw ps2"/><i className="pop-screw ps3"/><i className="pop-screw ps4"/><div className="popout-screen">{config.powered?(config.showGif?<img className="led-gif" src="/patrick-kane.gif" alt="Patrick Kane skating with the puck"/>:alert?<AlertDisplay alert={alert} config={config} onComplete={finishAlert}/>:<Matrix text={item.content} color={item.color} speed={config.speed} brightness={config.brightness} onComplete={()=>{if(config.advanceMode==='complete')step(1)}}/>):<span>DISPLAY OFF</span>}<b/></div><div className="pop-controls"><button onClick={()=>step(-1)} aria-label="Previous playlist item" title="Previous"><ChevronLeft/></button><span>{active%count+1}/{count}</span><button onClick={()=>step(1)} aria-label="Next playlist item" title="Next"><ChevronRight/></button></div></div></div>}
