'use client';

import { useEffect, useRef, useState } from 'react';
import { Activity, BarChart3, ChevronDown, Clock3, ExternalLink, Film, GripVertical, Image as ImageIcon, LayoutList, MessageSquareText, Newspaper, Pencil, Plus, Power, RefreshCw, Settings2, ShieldCheck, Timer, Trash2, Trophy, Users, X, Zap } from 'lucide-react';

type Item={id:number;name:string;type:string;color:string;content:string;meta:string};
type ScoreAlert={id:string;text:string};
type ScoreSnapshot={id:string;league:string;period:number;status:string;away:string;home:string;awayScore:number;homeScore:number};
const initial:Item[]=[
 {id:1,name:'Market pulse',type:'Finance',color:'#baff3c',content:'NVDA 173.88 +2.46%   AAPL 229.31 +0.84%   BTC 108,240 +3.12%',meta:'Dow 30 · Always'},
 {id:2,name:'Game night',type:'Sports',color:'#68a9ff',content:'BOS 112  ·  NYK 109  ·  4TH 02:14',meta:'NBA · Live scores'},
 {id:3,name:'Office welcome',type:'Message',color:'#ffb84d',content:'WELCOME TO NORTHSTAR CAPITAL  •  MARKETS IN MOTION',meta:'Every weekday · 8:00 AM–6:00 PM'},
 {id:4,name:'Business headlines',type:'RSS',color:'#ff6684',content:'GLOBAL MARKETS RALLY AS TECHNOLOGY SHARES LEAD GAINS',meta:'CNBC Top News · Title only'},
];

function LedCanvas({text,color,running,speed,brightness,onComplete}:{text:string;color:string;running:boolean;speed:number;brightness:number;onComplete:()=>void}){
 const ref=useRef<HTMLCanvasElement>(null),offset=useRef(0),completeRef=useRef(onComplete),liveContent=useRef({text,color});completeRef.current=onComplete;liveContent.current={text,color};
 useEffect(()=>{const c=ref.current,x=c?.getContext('2d');if(!c||!x)return;let raf=0,last=performance.now();
 const draw=(now:number)=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=r.width,h=r.height;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}x.setTransform(d,0,0,d,0,0);x.fillStyle='#020403';x.fillRect(0,0,w,h);if(running)offset.current-=(now-last)*(.015+speed*.011);last=now;
 const v=document.createElement('canvas');v.width=Math.max(1,Math.round(w));v.height=Math.max(1,Math.round(h));const q=v.getContext('2d')!,live=liveContent.current,plain=live.text.replace(/\[\[#[0-9a-f]{6}\]\]/gi,'');q.fillStyle='#000';q.fillRect(0,0,w,h);q.textBaseline='middle';q.font=`800 ${Math.max(24,h*.39)}px ui-monospace,Menlo,monospace`;const tw=q.measureText(plain).width+180;if(offset.current<-(tw+w)){offset.current=0;completeRef.current()}let cursor=w+offset.current,ink=live.color;for(const part of live.text.split(/(\[\[#[0-9a-f]{6}\]\])/gi)){const tag=part.match(/^\[\[(#[0-9a-f]{6})\]\]$/i);if(tag){ink=tag[1];continue}q.fillStyle=ink;q.shadowColor=ink;q.shadowBlur=8;q.fillText(part,cursor,h/2);cursor+=q.measureText(part).width}
 const data=q.getImageData(0,0,v.width,v.height).data,s=Math.max(2.2,Math.min(4.2,w/245)),p=s*1.72;x.globalAlpha=.45+brightness/180;
 for(let yy=p/2;yy<h;yy+=p)for(let xx=p/2;xx<w;xx+=p){const i=(Math.min(v.height-1,yy|0)*v.width+Math.min(v.width-1,xx|0))*4,rr=data[i],g=data[i+1],b=data[i+2];x.beginPath();x.arc(xx,yy,s/2,0,Math.PI*2);if(rr+g+b>25){x.shadowColor=`rgb(${rr},${g},${b})`;x.shadowBlur=s*2;x.fillStyle=`rgb(${rr},${g},${b})`}else{x.shadowBlur=0;x.fillStyle='#18201b'}x.fill()}x.globalAlpha=1;x.shadowBlur=0;raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[running,speed,brightness]);return <canvas ref={ref} className="led"/>}

const typeIcon=(type:string)=>type==='Finance'?<BarChart3/>:type==='Sports'?<Trophy/>:type==='RSS'?<Newspaper/>:<MessageSquareText/>;
function AlertDisplay({alert,speed,brightness,onComplete}:{alert:ScoreAlert;speed:number;brightness:number;onComplete:()=>void}){const[ready,setReady]=useState(false);useEffect(()=>{setReady(false);const id=setTimeout(()=>setReady(true),1800);return()=>clearTimeout(id)},[alert.id]);return ready?<LedCanvas text={alert.text} color="#ff3b3b" running speed={speed} brightness={brightness} onComplete={onComplete}/>:<div className="score-alert-flash">SCORE ALERT</div>}

const sportPaths:Record<string,string>={NFL:'football/nfl',MLB:'baseball/mlb',NBA:'basketball/nba',NHL:'hockey/nhl',MLS:'soccer/usa.1',NCAAF:'football/college-football'};
const ymd=(date:Date)=>`${date.getUTCFullYear()}${String(date.getUTCMonth()+1).padStart(2,'0')}${String(date.getUTCDate()).padStart(2,'0')}`;
const clockLabel=(value:string)=>new Date(`2000-01-01T${value}:00`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const eventRank=(event:any)=>Math.min(...(event.competitions?.[0]?.competitors||[]).map((team:any)=>team.curatedRank?.current||99));
const formatGame=(event:any,league:string)=>{const c=event.competitions?.[0],teams=c?.competitors||[],away=teams.find((t:any)=>t.homeAway==='away'),home=teams.find((t:any)=>t.homeAway==='home'),state=c?.status?.type?.state||event.status?.type?.state||'pre',status=c?.status?.type?.shortDetail||event.status?.type?.shortDetail||'',rank=(team:any)=>team?.curatedRank?.current||99,name=(team:any)=>{if(!team)return'TBD';if(league!=='NCAAF')return team.team?.abbreviation||'TBD';const full=team.team?.shortDisplayName||team.team?.displayName||team.team?.abbreviation||'TBD';return rank(team)<=25?`#${rank(team)} ${full}`:full};if(state==='pre')return `${name(away)}@${name(home)}  ${status}`;let first=away,second=home;if(league==='NCAAF'&&rank(home)<rank(away)){first=home;second=away}return `${name(first)} ${first?.score||''}  ${name(second)} ${second?.score||''}  ${status}`};
async function browserSports(selected:string,includeYesterday:boolean,collegeTeams:string[]){
 const nowParts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));
 const localNoon=new Date(`${nowParts.year}-${nowParts.month}-${nowParts.day}T12:00:00Z`),dayIndex=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(nowParts.weekday),afterNoon=+nowParts.hour>=12;
 const fetchRange=async(league:string,start:Date,end:Date)=>{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${sportPaths[league]}/scoreboard?dates=${ymd(start)}-${ymd(end)}`);if(!r.ok)throw new Error();return (await r.json()).events||[]};
 const leagues=selected==='ALL'?Object.keys(sportPaths):[selected];let priorCount=0,currentCount=0,priorApplied=false;const sections:{league:string;label:string;events:any[]}[]=[];
 await Promise.all(leagues.map(async league=>{try{
   if(league==='NFL'||league==='NCAAF'){
    const daysSinceThursday=(dayIndex+3)%7,thursday=new Date(localNoon);thursday.setUTCDate(thursday.getUTCDate()-daysSinceThursday);const switched=daysSinceThursday>0||(dayIndex===4&&(+nowParts.hour>0||+nowParts.minute>=1)),rangeStart=new Date(thursday);if(!switched)rangeStart.setUTCDate(rangeStart.getUTCDate()-7);const rangeEnd=new Date(rangeStart);rangeEnd.setUTCDate(rangeEnd.getUTCDate()+(league==='NFL'?6:3));let events=await fetchRange(league,rangeStart,rangeEnd);
    if(league==='NFL')events.sort((a:any,b:any)=>switched?((a.status?.type?.state==='pre'?1:0)-(b.status?.type?.state==='pre'?1:0)||+new Date(a.date)-+new Date(b.date)):+new Date(b.date)-+new Date(a.date));
    else{const custom=collegeTeams.filter(Boolean);events=events.filter((e:any)=>eventRank(e)<=25||(e.competitions?.[0]?.competitors||[]).some((t:any)=>custom.includes(t.team?.abbreviation))).sort((a:any,b:any)=>eventRank(a)-eventRank(b)||+new Date(a.date)-+new Date(b.date))}
    if(switched)currentCount+=events.length;else{priorCount+=events.length;priorApplied=true}sections.push({league,label:switched?'THIS WEEK':'LAST WEEK',events});return;
   }
   const yesterday=new Date(localNoon);yesterday.setUTCDate(yesterday.getUTCDate()-1);const todayEvents=await fetchRange(league,localNoon,localNoon),live=todayEvents.some((e:any)=>e.status?.type?.state==='in'),usePrior=includeYesterday&&(!afterNoon||!live),priorEvents=usePrior?await fetchRange(league,yesterday,yesterday):[];priorCount+=priorEvents.length;currentCount+=todayEvents.length;priorApplied||=usePrior;if(priorEvents.length)sections.push({league,label:'YESTERDAY',events:priorEvents});if(todayEvents.length)sections.push({league,label:'TODAY',events:todayEvents});
  }catch{return}}));
 const priority=(event:any)=>event.status?.type?.state==='in'?0:event.status?.type?.state==='post'?1:2;for(const section of sections)section.events.sort((a:any,b:any)=>priority(a)-priority(b)||(section.league==='NCAAF'?eventRank(a)-eventRank(b):+new Date(a.date)-+new Date(b.date)));
 const text=sections.map(section=>`${section.label} ${section.league}   ${section.events.map(event=>{const state=event.status?.type?.state,color=state==='in'?'#65ff65':state==='post'?'#7f9bb3':'#ffbd55',label=state==='in'?'LIVE':state==='post'?'FINAL':'UPCOMING';return `[[${color}]]${label}  ${formatGame(event,section.league)}`}).join('   •   ')}`).join('   ◆   ');
 const snapshots:ScoreSnapshot[]=sections.flatMap(section=>section.events.filter((e:any)=>e.status?.type?.state==='in').map((e:any)=>{const c=e.competitions?.[0],teams=c?.competitors||[],away=teams.find((t:any)=>t.homeAway==='away'),home=teams.find((t:any)=>t.homeAway==='home');return{id:String(e.id),league:section.league,period:Number(c?.status?.period||e.status?.period||0),status:c?.status?.type?.shortDetail||e.status?.type?.shortDetail||'IN PROGRESS',away:away?.team?.abbreviation||'AWAY',home:home?.team?.abbreviation||'HOME',awayScore:Number(away?.score||0),homeScore:Number(home?.score||0)}}));
 return {text:text||'NO GAMES SCHEDULED',yesterdayCount:priorCount,todayCount:currentCount,yesterdayApplied:priorApplied,afterNoonET:afterNoon,snapshots};
}

export default function Home(){
 const audioRef=useRef<HTMLAudioElement|null>(null),alertAudioRef=useRef<HTMLAudioElement|null>(null);
 const scoresRef=useRef(new Map<string,ScoreSnapshot>()),alertRef=useRef<ScoreAlert|null>(null),alertQueue=useRef<ScoreAlert[]>([]);
 const[items,setItems]=useState(initial),[active,setActive]=useState(0),[powered,setPowered]=useState(true),[gifMode,setGifMode]=useState(false),[detectorOn,setDetectorOn]=useState(false),[scoreAlert,setScoreAlert]=useState<ScoreAlert|null>(null),[speed,setSpeed]=useState(5),[brightness,setBrightness]=useState(82),[dirty,setDirty]=useState(false),[modal,setModal]=useState(false),[scheduleOpen,setScheduleOpen]=useState(false),[scheduleEnabled,setScheduleEnabled]=useState(true),[scheduleStart,setScheduleStart]=useState('08:00'),[scheduleEnd,setScheduleEnd]=useState('22:00'),[editing,setEditing]=useState<number|null>(null),[messageDraft,setMessageDraft]=useState(''),[toast,setToast]=useState(''),[syncing,setSyncing]=useState(true),[updated,setUpdated]=useState('Connecting…'),[advanceMode,setAdvanceMode]=useState<'time'|'complete'>('complete'),[intervalSeconds,setIntervalSeconds]=useState(20),[league,setLeague]=useState('ALL'),[showYesterday,setShowYesterday]=useState(true),[sportsPolicy,setSportsPolicy]=useState('Eastern-time rule active'),[scoreCounts,setScoreCounts]=useState({yesterday:0,today:0}),[collegeTeams,setCollegeTeams]=useState(['','', '']),[customOn,setCustomOn]=useState(false),[symbols,setSymbols]=useState(['AAPL','NVDA','MSFT','TSLA','AMZN','META','GOOGL','NFLX','AMD','INTC']);
 const playAlertSound=()=>{if(!alertAudioRef.current)alertAudioRef.current=new Audio('/score-alert.mp3');alertAudioRef.current.currentTime=0;void alertAudioRef.current.play().catch(()=>{})};
 const pushAlert=(alert:ScoreAlert)=>{localStorage.setItem('signal-score-alert',JSON.stringify(alert));if(alertRef.current)alertQueue.current.push(alert);else{alertRef.current=alert;setScoreAlert(alert);playAlertSound()}};
 const finishAlert=()=>{const next=alertQueue.current.shift()||null;alertRef.current=next;setScoreAlert(next);if(next)playAlertSound()};
 const current=items[active%items.length]||initial[0];
 useEffect(()=>{if(!scheduleEnabled)return;const check=()=>{const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value])),now=+parts.hour*60 + +parts.minute,[sh,sm]=scheduleStart.split(':').map(Number),[eh,em]=scheduleEnd.split(':').map(Number),start=sh*60+sm,end=eh*60+em,on=start<=end?now>=start&&now<end:now>=start||now<end;setPowered(previous=>{if(previous===on)return previous;try{const saved=JSON.parse(localStorage.getItem('signal-popout')||'{}');localStorage.setItem('signal-popout',JSON.stringify({...saved,powered:on,revision:Date.now()}))}catch{}return on})};check();const id=setInterval(check,30000);return()=>clearInterval(id)},[scheduleEnabled,scheduleStart,scheduleEnd]);
 useEffect(()=>{if(!powered||scoreAlert||items.length<2||advanceMode!=='time')return;const id=setInterval(()=>setActive(v=>(v+1)%items.length),intervalSeconds*1000);return()=>clearInterval(id)},[powered,scoreAlert,items.length,advanceMode,intervalSeconds]);
 useEffect(()=>{let alive=true;const sync=async()=>{setSyncing(true);try{const params=new URLSearchParams({league,yesterday:showYesterday?'1':'0'});if(customOn)params.set('symbols',symbols.filter(Boolean).join(','));const [response,sport]=await Promise.all([fetch(`/api/live?${params}`),browserSports(league,showYesterday,collegeTeams)]);if(!response.ok)throw new Error();const data=await response.json();if(!alive)return;setItems(previous=>{const next=previous.map(item=>item.type==='Finance'?{...item,content:data.markets,meta:`${data.symbols.length} quotes · Live · ${data.live.markets?'Connected':'Fallback'}`}:item.type==='Sports'?{...item,content:sport.text,meta:`${league==='ALL'?'All leagues':league} · Weekly rules active · Live`}:item.type==='RSS'?{...item,content:data.news,meta:`Top 7 CNBC headlines · ${data.live.news?'Live':'Fallback'}`}:item);localStorage.setItem('signal-live-items',JSON.stringify({items:next,revision:Date.now()}));return next});setScoreCounts({yesterday:sport.yesterdayCount,today:sport.todayCount});setSportsPolicy(league==='NFL'?'NFL Thursday-week rule':league==='NCAAF'?'Top 25 Thursday-week rule':!showYesterday?'Yesterday off':sport.yesterdayApplied?'Showing yesterday + today':sport.afterNoonET?'Past noon · live leagues suppress yesterday':'Today only');setUpdated(new Date(data.updatedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}))}catch{if(alive){setUpdated('Retrying…');setSportsPolicy('Sports source reconnecting')}}finally{if(alive)setSyncing(false)}};sync();const timer=setInterval(sync,60000);return()=>{alive=false;clearInterval(timer)}},[league,showYesterday,collegeTeams.join(','),customOn,symbols.join(',')]);
 useEffect(()=>{if(!detectorOn){scoresRef.current.clear();return}let alive=true;const detect=async()=>{const sport=await browserSports('ALL',false,collegeTeams);if(!alive)return;for(const game of sport.snapshots){const prior=scoresRef.current.get(game.id),awayScored=!!prior&&game.awayScore>prior.awayScore,homeScored=!!prior&&game.homeScore>prior.homeScore,scorer=awayScored?game.away:homeScored?game.home:'',before=prior?prior.awayScore-prior.homeScore:0,after=game.awayScore-game.homeScore,goAhead=(awayScored&&before<=0&&after>0)||(homeScored&&before>=0&&after<0),oneScore=game.league==='NFL'||game.league==='NCAAF'?8:1,late=game.league==='MLB'?game.period>=7:game.period>=(game.league==='NHL'?3:game.league==='NFL'||game.league==='NCAAF'?4:2),clock=game.status.match(/(\d+):(\d+)/),seconds=clock?(+clock[1]*60)+ +clock[2]:9999,nbaClutch=game.league==='NBA'&&game.period>=4&&seconds<=120&&(goAhead||after===0),highValue=game.league==='NBA'?nbaClutch:goAhead||(late&&Math.abs(after)<=oneScore);if(scorer&&highValue){let description=`${scorer} scores`;try{const summary=await fetch(`https://site.api.espn.com/apis/site/v2/sports/${sportPaths[game.league]}/summary?event=${game.id}`).then(r=>r.json()),plays:any[]=[];const walk=(v:any)=>{if(!v||typeof v!=='object')return;if(v.scoringPlay&&typeof v.text==='string')plays.push(v);Object.values(v).forEach(walk)};walk(summary);description=plays.at(-1)?.text||description}catch{}pushAlert({id:`${game.id}-${game.awayScore}-${game.homeScore}`,text:`${game.league}  ${game.away}@${game.home}   •   ${game.status}   —   ${description}   •   ${game.away} ${game.awayScore}  ·  ${game.home} ${game.homeScore}`})}scoresRef.current.set(game.id,game)}};void detect();const timer=setInterval(()=>void detect(),15000);return()=>{alive=false;clearInterval(timer)}},[detectorOn,collegeTeams.join(',')]);
 const writePopout=(showGif=gifMode)=>localStorage.setItem('signal-popout',JSON.stringify({items,speed,brightness,advanceMode,intervalSeconds,powered,showGif,detectorOn,revision:Date.now()}));
 const publish=()=>{writePopout();setDirty(false);setToast('Published — pop-out refreshed');setTimeout(()=>setToast(''),3200)};
 const popout=()=>{writePopout();window.open('/ticker','signal-ticker','popup=yes,width=1200,height=260,menubar=no,toolbar=no,location=no,status=no,scrollbars=no,resizable=yes')};
 const toggleGif=()=>{const next=!gifMode;setGifMode(next);writePopout(next);if(next){audioRef.current?.pause();const audio=new Audio('/gravy-train.mp3');audioRef.current=audio;void audio.play().catch(()=>setToast('Press Play Highlight again to allow sound'))}else{audioRef.current?.pause();if(audioRef.current)audioRef.current.currentTime=0}};
 const move=(i:number,dir:number)=>{const to=i+dir;if(to<0||to>=items.length)return;const a=[...items];[a[i],a[to]]=[a[to],a[i]];setItems(a);setDirty(true);setActive(0)};
 const add=(type:string)=>{const item:Item={id:Date.now(),name:type==='Message'?'New announcement':`New ${type.toLowerCase()} feed`,type,color:type==='Sports'?'#68a9ff':type==='Finance'?'#baff3c':type==='RSS'?'#ff6684':'#ffb84d',content:type==='Message'?'WELCOME — YOUR MESSAGE GOES HERE':type==='Sports'?'LIVE SCORES  •  NEXT GAME 7:30 PM':type==='RSS'?'LATEST HEADLINES  •  NEWS FEED CONNECTED':'S&P 500 5,648.40 +0.62%',meta:'Always · Draft'};setItems(v=>[...v,item]);setDirty(true);setModal(false)};
 const remove=(id:number)=>{if(items.length===1){setToast('Keep at least one playlist item');setTimeout(()=>setToast(''),2600);return}const index=items.findIndex(x=>x.id===id);setItems(v=>v.filter(x=>x.id!==id));setActive(v=>Math.min(v,index>0?items.length-2:0));setDirty(true)};
 const openEditor=(item:Item)=>{setEditing(item.id);setMessageDraft(item.content)};
 const saveMessage=()=>{setItems(v=>v.map(item=>item.id===editing?{...item,content:messageDraft.trim()||'WELCOME',meta:'Office message · Always'}:item));setEditing(null);setDirty(true)};
 return <main>
  <aside className="rail"><div className="logo"><Zap fill="currentColor"/></div><nav><button className="selected" aria-label="Displays"><Activity/></button><button aria-label="Playlists"><LayoutList/></button><button aria-label="Users"><Users/></button><button aria-label="Settings"><Settings2/></button></nav><div className="avatar">DN</div></aside>
  <div className="workspace">
   <header><div><div className="crumb">DISPLAYS <span>/</span> LOBBY TICKER</div><h1>Lobby ticker</h1></div><div className="header-actions"><span className="online"><i/>ONLINE</span><button className="icon-btn" onClick={()=>setPowered(v=>!v)} title={powered?'Power off':'Power on'}><Power/></button><button className="publish" onClick={publish} disabled={!dirty}>{dirty?'Publish changes':'Published'}<Zap size={14} fill="currentColor"/></button></div></header>
   <section className="preview-card">
    <div className="card-head"><div><span>LIVE PREVIEW</span><strong>{gifMode?'Patrick Kane highlight':current.name}</strong></div><div className="spec"><button className={`gif-button ${gifMode?'on':''}`} onClick={toggleGif}><Film/> {gifMode?'RETURN TO TICKER':'PLAY HIGHLIGHT'}</button><button className="popout" onClick={popout}><ExternalLink/> POP OUT</button><span className="feed-sync"><RefreshCw className={syncing?'spin':''}/> UPDATED {updated}</span><span>64 PX</span><span><ShieldCheck/> SECURE</span></div></div>
    <div className={`ticker-stage ${powered?'':'off'}`}><div className="hanger h1"/><div className="hanger h2"/><div className="ticker"><b className="screw s1"/><b className="screw s2"/><b className="screw s3"/><b className="screw s4"/><div className="screen">{powered?(gifMode?<img className="led-gif" src="/patrick-kane.gif" alt="Patrick Kane skating with the puck"/>:scoreAlert?<AlertDisplay alert={scoreAlert} speed={speed} brightness={brightness} onComplete={finishAlert}/>:<LedCanvas text={current.content} color={current.color} running={powered} speed={speed} brightness={brightness} onComplete={()=>{if(advanceMode==='complete')setActive(v=>(v+1)%items.length)}}/>):<div className="powered-off">DISPLAY OFF</div>}<div className="glare"/></div><small>R/64</small></div></div>
    <div className="quick-controls"><label><span>BRIGHTNESS <b>{brightness}%</b></span><input type="range" min="10" max="100" value={brightness} onChange={e=>{setBrightness(+e.target.value);setDirty(true)}}/></label><label><span>SCROLL SPEED <b>{speed}</b></span><input type="range" min="1" max="10" value={speed} onChange={e=>{setSpeed(+e.target.value);setDirty(true)}}/></label><div className="schedule"><Clock3/><span>POWER SCHEDULE<b>{scheduleEnabled?`${clockLabel(scheduleStart)} — ${clockLabel(scheduleEnd)} ET`:'DISABLED'}</b></span><button onClick={()=>setScheduleOpen(true)}>EDIT</button></div></div>
   </section>
   <section className="rules-panel"><div className="rules-title"><div><Timer/><span><strong>Playback rules</strong><small>Choose when each playlist item advances</small></span></div><span className="saved-dot">● AUTO-SAVED</span></div><div className="rule-grid">
    <div className="rule-block"><label>ADVANCE PLAYLIST</label><div className="segmented"><button className={advanceMode==='time'?'on':''} onClick={()=>{setAdvanceMode('time');setDirty(true)}}>After a set time</button><button className={advanceMode==='complete'?'on':''} onClick={()=>{setAdvanceMode('complete');setDirty(true)}}>After full content pass</button></div>{advanceMode==='time'?<div className="inline-field"><span>Change every</span><input type="number" min="5" max="300" value={intervalSeconds} onChange={e=>{setIntervalSeconds(Math.max(5,+e.target.value));setDirty(true)}}/><b>seconds</b></div>:<p className="rule-note">The next item begins only after every score, headline, or quote has scrolled completely.</p>}</div>
    <div className="rule-block"><label>SPORTS COVERAGE</label><div className="select-field"><select value={league} onChange={e=>{setLeague(e.target.value);setDirty(true)}}>{['ALL','NFL','MLB','NBA','NHL','MLS','NCAAF'].map(x=><option key={x} value={x}>{x==='ALL'?'All supported leagues':x}</option>)}</select><ChevronDown/></div><div className="score-counts"><button onClick={()=>{const i=items.findIndex(x=>x.type==='Sports');if(i>=0)setActive(i)}}><b>{scoreCounts.yesterday}</b><span>{league==='NFL'||league==='NCAAF'?'LAST WEEK':'YESTERDAY'}</span></button><button onClick={()=>{const i=items.findIndex(x=>x.type==='Sports');if(i>=0)setActive(i)}}><b>{scoreCounts.today}</b><span>{league==='NFL'||league==='NCAAF'?'THIS WEEK':'TODAY'}</span></button></div>{league!=='NFL'&&league!=='NCAAF'&&<div className="sports-rule"><span><b>Include yesterday before noon ET</b><small>After noon, hide yesterday per league once live games begin.</small></span><button className={`switch ${showYesterday?'on':''}`} onClick={()=>{setShowYesterday(v=>!v);setDirty(true)}} aria-label="Toggle yesterday's scores"><i/></button></div>}{(league==='NCAAF'||league==='ALL')&&<div className="college-custom"><b>NCAAF CUSTOM TEAMS</b><span>{collegeTeams.map((team,i)=><input key={i} value={team} placeholder="TEAM" maxLength={5} aria-label={`Custom college team ${i+1}`} onChange={e=>{const next=[...collegeTeams];next[i]=e.target.value.toUpperCase().replace(/[^A-Z]/g,'');setCollegeTeams(next);setDirty(true)}}/>)}</span><small>Top 25 teams are always included.</small></div>}<p className="policy-status">{sportsPolicy}</p></div>
    <div className="rule-block watchlist"><div className="toggle-line"><label>LIVE SCORE DETECTOR</label><button className={`switch ${detectorOn?'on':''}`} onClick={()=>{const next=!detectorOn;setDetectorOn(next);setDirty(true);if(next){const audio=new Audio('/score-alert.mp3');audio.volume=0;alertAudioRef.current=audio;void audio.play().then(()=>{audio.pause();audio.currentTime=0;audio.volume=1}).catch(()=>{})}}} aria-label="Toggle live score detector"><i/></button></div><p className="rule-note">{detectorOn?'All leagues active. NBA uses clutch mode: ties and lead changes in the final 2:00 only.':'Off — live games will not interrupt the playlist.'}</p><div className="detector-divider"/><div className="toggle-line"><label>CUSTOM QUOTE PANEL</label><button className={`switch ${customOn?'on':''}`} onClick={()=>{setCustomOn(v=>!v);setDirty(true)}} aria-label="Toggle custom quotes"><i/></button></div><p className="rule-note">{customOn?'Using your custom symbols (up to 10).':'Off — showing the default top 10 quotes.'}</p>{customOn&&<div className="symbols">{symbols.map((symbol,i)=><input key={i} value={symbol} maxLength={6} aria-label={`Stock symbol ${i+1}`} onChange={e=>{const next=[...symbols];next[i]=e.target.value.toUpperCase().replace(/[^A-Z.]/g,'');setSymbols(next);setDirty(true)}}/>)}</div>}</div>
   </div></section>
   <section className="content-panel"><div className="section-head"><div><h2>Playlist</h2><p>{items.length} items · Plays in order</p></div><button className="add" onClick={()=>setModal(true)}><Plus/>Add content</button></div>
    <div className="playlist-head"><span>CONTENT</span><span>SCHEDULE / SOURCE</span><span>STATUS</span><span/></div>
    <div className="playlist">{items.map((item,i)=><article key={item.id} className={i===active?'active':''} onClick={()=>setActive(i)}><GripVertical className="grip"/><div className="type-icon" style={{color:item.color,background:`${item.color}18`}}>{typeIcon(item.type)}</div><div className="item-name"><strong>{item.name}</strong><span>{item.type}</span></div><div className="meta">{item.meta}</div><div className="state"><i/>ACTIVE</div><div className="row-actions"><button onClick={e=>{e.stopPropagation();move(i,-1)}} aria-label="Move up">↑</button><button onClick={e=>{e.stopPropagation();move(i,1)}} aria-label="Move down">↓</button>{item.type==='Message'&&<button onClick={e=>{e.stopPropagation();openEditor(item)}} aria-label="Edit message"><Pencil/></button>}<button onClick={e=>{e.stopPropagation();remove(item.id)}} aria-label={`Delete ${item.name}`}><Trash2/></button></div></article>)}</div>
   </section>
  </div>
  {modal&&<div className="modal-bg" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}><X/></button><span className="modal-kicker">NEW PLAYLIST ITEM</span><h2>What do you want to show?</h2><p>Choose a content source. You can customize it before publishing.</p><div className="choices">{[['Message','Write custom text'],['Finance','Markets & watchlists'],['Sports','Scores & schedules'],['RSS','Live news headlines']].map(([type,desc])=><button key={type} onClick={()=>add(type)}><div>{typeIcon(type)}</div><strong>{type}</strong><span>{desc}</span></button>)}<button><div><ImageIcon/></div><strong>Image</strong><span>Logo or pixel artwork</span></button><button><div><ChevronDown/></div><strong>More sources</strong><span>Sheets & custom API</span></button></div></div></div>}
  {editing!==null&&<div className="modal-bg" onMouseDown={()=>setEditing(null)}><div className="modal message-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setEditing(null)}><X/></button><span className="modal-kicker">OFFICE WELCOME MESSAGE</span><h2>Update the lobby greeting</h2><p>This text will stay in draft until you click Publish changes.</p><textarea autoFocus value={messageDraft} maxLength={240} onChange={e=>setMessageDraft(e.target.value)} aria-label="Office welcome message"/><div className="message-actions"><small>{messageDraft.length}/240</small><button onClick={()=>setEditing(null)}>Cancel</button><button className="save-message" onClick={saveMessage}>Save message</button></div></div></div>}
  {scheduleOpen&&<div className="modal-bg" onMouseDown={()=>setScheduleOpen(false)}><div className="modal schedule-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setScheduleOpen(false)}><X/></button><span className="modal-kicker">POWER SCHEDULE</span><h2>Set display hours</h2><p>Times use Eastern Time. Overnight schedules are supported.</p><div className="schedule-toggle"><span><b>Automatic schedule</b><small>Turn the ticker on and off at these times.</small></span><button className={`switch ${scheduleEnabled?'on':''}`} onClick={()=>setScheduleEnabled(v=>!v)} aria-label="Toggle power schedule"><i/></button></div><div className="time-fields"><label>TURN ON<input type="time" value={scheduleStart} onChange={e=>setScheduleStart(e.target.value)}/></label><label>TURN OFF<input type="time" value={scheduleEnd} onChange={e=>setScheduleEnd(e.target.value)}/></label></div><div className="message-actions"><button onClick={()=>setScheduleOpen(false)}>Cancel</button><button className="save-message" onClick={()=>{setScheduleOpen(false);setDirty(true)}}>Save schedule</button></div></div></div>}
  {toast&&<div className="toast"><span>✓</span>{toast}</div>}
 </main>
}
